routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::resource('post', 'PostController');
Route::resource('comment', 'CommentController')->only([
    'store', 'destroy'
]);

app/Models/Comment.php
<?php
namespace App\Models;
use Eloquent;

class Comment extends Eloquent
{
  protected $fillable = [ 'id', 'content', 'user_id', 'post_id' ];
    /**
     * One to Many relation
     *
     * @return Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    /**
     * One to Many relation
     *
     * @return Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function post()
    {
        return $this->belongsTo('App\Models\Post');
    }
}

app/Models/Post.php
<?php
namespace App\Models;
use Eloquent;

class Post extends Eloquent
{
    protected $fillable = [ 'id', 'title', 'slug', 'content', 'user_id' ];

    /**
     * One to Many relation
     *
     * @return Illuminate\Database\Eloquent\Relations\hasMany
     */
    public function comments()
    {
      return $this->hasMany('App\Models\Comment');
    }
    /**
     * One to Many relation
     *
     * @return Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }
}

app/Models/User.php
<?php
namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Notifications\NewComment as NewCommentNotification;

class User extends Authenticatable
{
  use Notifiable;

  protected $fillable = [ 'name', 'email', 'password', 'remember_token' ];
  protected $hidden = [ 'password', 'remember_token' ];

  /**
   * One to Many relation
   *
   * @return Illuminate\Database\Eloquent\Relations\hasMany
   */
  public function posts()
  {
    return $this->hasMany('App\Models\Post');
  }

  /**
   * One to Many relation
   *
   * @return Illuminate\Database\Eloquent\Relations\hasMany
   */
  public function comments()
  {
    return $this->hasMany('App\Models\Comment');
  }

  public function sendNewCommentNotification($input)
  {
      $this->notify(new NewCommentNotification($input));
  }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller as BaseController;
use App\Models\Comment;
use App\Models\Post;
use App\Models\User;
use Validate;
use Session;

class CommentController extends BaseController {

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
       $request->validate([
            'content' => 'required'
       ]);
       $input = $request->all();

       $comment = Comment::create($input);
       Session::flash('message', 'Message reçu !');

       //send notif
       $post = Post::find($input['post_id']);
       $user = User::find($post->user_id);

       $user->sendNewCommentNotification($input);
       return redirect()->route('post.show', $comment->post_id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
      Comment::destroy($id);
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Post;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        // $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();
        return view('index', compact('posts'));
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller as BaseController;
use Auth;
use App\Models\Post;
use Validate;
use Session;

class PostController extends BaseController {

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $posts = Post::all();
        return view('post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $user = Auth::user();
        if($user !== null){
          return view('post.create', compact('user'));
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
       $request->validate([
            'title' => 'required',
            'content' => 'required'
       ]);
       $input = $request->all();
       $input['slug'] = str_slug($input['title'], '-');
       $post = Post::create($input);

       Session::flash('message', 'Article créé !');

       return redirect()->route('post.show', $post->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $user = Auth::user();
        $post = Post::find($id);
        return view('post.show', compact('post','user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $user = Auth::user();
        if($user !== null){
          $post = Post::find($id);
          return view('post.edit', compact('post','user'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id, Request $request)
    {
       $request->validate([
            'title' => 'required',
            'content' => 'required'
       ]);
       $input = $request->all();

       $post = Post::find($id);
       $post->update($input);
       Session::flash('message', 'Modification effectuée !');

       return redirect()->route('post.show', $post->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
      Post::destroy($id);
    }

}

resources/views/index.blade.php
@extends('layout.layout')
@section('title')
  Blog Laravel par Valentin Rocher
@endsection
@section('content')
<div class="flex-center position-ref full-height">

<div class="container" style="min-height:570px;">
  <h1 class="text-center mt-2 mb-4">Nos derniers articles</h1>
    @empty($posts)
      <div class="offset-md-1 row">
        @foreach($posts as $key => $post)
        <div class="card col-lg-3 m-4" style="min-height: 8rem;">
          <div class="card-body">
            <h5 class="card-title">{{ $post->title }}</h5>
            <p class="card-text">{{ str_limit( $post->content, 100, '...') }}</p>
            <a href="{{ route('post.show', ['post' => $post->id ])}}" class="btn btn-primary">En savoir plus</a>
          </div>
        </div>
        @endforeach
      </div>
    @else
      <p class="text-center">Coming soon</p>
    @endif
</div>
@endsection

resources/views/layout/footer.blade.php
<footer class="p-3 mt-4 footer">
  <hr>
Valentin Rocher - 2018
</footer>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
@yield('scripts')
</body>
</html>

resources/views/layout/header.blade.php
<head>
    <meta charset="UTF-8">
    <title>@yield('title') - Anoblog</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    @yield('styles')
</head>
<body>
<div class="header">
  <nav class="navbar navbar-dark col-lg-6 m-auto">
    <a href="{{ route('home') }}" class="nav-link">Accueil</a>
    <!-- <a href="{{ route('post.index') }}" class="nav-link">Article au hasard</a> -->
    @if (Route::has('login'))
            @auth
                <!-- <a href="{{ route('post.create') }}" class="nav-link">Créer un nouvel article</a> -->
                <a href="{{ route('post.index') }}" class="nav-link">Admin</a>
                <a class="nav-link" href="{{ route('logout') }}"
                  onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Déconnexion</a>
                  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                      @csrf
                  </form>
            @else
                <a href="{{ route('login') }}" class="nav-link">Se connecter</a>
                <a href="{{ route('register') }}" class="nav-link">S'inscrire</a>
            @endauth
    @endif
  </nav>
</div>

resources/views/layout/layout.blade.php
<!DOCTYPE html>
<html lang="fr">
@include('layout.header')

@yield('content')

@include('layout.footer')

resources/views/post/create.blade.php
@extends('layout.layout')
@section('title')
Article - Création
@endsection
@section('content')
<div class="container" style="min-height:570px;">
    {{ Form::open(['route' => 'post.store', 'autocomplete' => 'off']) }}
        <div class="row">
            <div class="offset-md-3 col-md-9 col-lg-9">
                <div class="box box-primary">
                    <div class="box-header">
                        <h1 class="box-title">Création d'un article de blog</h1>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-6 col-lg-6">
                                {!! Form::hidden('user_id', $user->id) !!}
                                <div class="form-group {{ $errors->has('last_name') ? 'has-error' : '' }}">
                                    {{ Form::label('title', 'Titre') }}
                                    {{ Form::text('title', old('title'), ['class' => 'form-control', 'autofocus']) }}
                                    {!! $errors->first('title','<p class="text-danger"><strong>:message</strong></p>') !!}
                                </div>
                                <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                                    {{ Form::label('content', 'Texte') }}
                                    {{ Form::textarea('content', old('content'), ['class' => 'form-control']) }}
                                    {!! $errors->first('content','<p class="text-danger"><strong>:message</strong></p>') !!}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-sm-6 offset-md-3 mbl">
                <span class="btn-group pull-right">
                    <button type="submit" class="btn btn-primary">
                        Sauver
                    </button>
                </span>
            </div>
        </div>
    {{ Form::close() }}
</div>
@endsection

resources/views/post/edit.blade.php
@extends('layout.layout')
@section('title')
{{ $post->title }} - Édition
@endsection
@section('content')
<div class="container" style="min-height:570px;">
    {{ Form::open(['route' => ['post.update', $post->id], 'method' => 'put', 'autocomplete' => 'off']) }}
        <div class="row">
            <div class="offset-md-3 col-md-9 col-lg-9">
                <div class="box box-primary">
                    <div class="box-header">
                        <h1 class="box-title">Édition d'un article de blog</h1>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-6 col-lg-6">
                                <div class="form-group {{ $errors->has('last_name') ? 'has-error' : '' }}">
                                    {{ Form::label('title', 'Titre') }}
                                    {{ Form::text('title', old('title', $post->title), ['class' => 'form-control', 'autofocus']) }}
                                    {!! $errors->first('title','<p class="text-danger"><strong>:message</strong></p>') !!}
                                </div>
                                <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                                    {{ Form::label('content', 'Texte') }}
                                    {{ Form::textarea('content', old('content', $post->content), ['class' => 'form-control']) }}
                                    {!! $errors->first('content','<p class="text-danger"><strong>:message</strong></p>') !!}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-sm-6 offset-md-3 mbl">
                <a href="{{ route("post.show", $post->id) }}" class="btn btn-success">
                    Retour à l'article
                </a>
                <span class="btn-group pull-right">
                    <button type="submit" class="btn btn-primary">
                        Sauver
                    </button>
                </span>
            </div>
        </div>
    {{ Form::close() }}
</div>
@endsection

resources/views/post/index.blade.php
@extends('layout.layout')
@section('title')
 Liste des Articles
@endsection
@section('content')
<div class="flex-center position-ref full-height">

  <div class="container" style="min-height:570px;">
    <h1 class="text-center mt-2 mb-4">Listes des articles <a href="{{route('post.create')}}" class="btn btn-primary">➕ Nouveau</a></h1>
    @if(Session::has('message'))
      <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
    @endif

      @empty($posts)
      <table class="table">
        <thead>
          <th>Id</th>
          <th>Titre</th>
          <th>Contenu</th>
          <th>Créateur</th>
          <th>Actions</th>
        </thead>
        <tbody>
          @foreach($posts as $post)
            <tr>
              <td>{{$post->id}}</td>
              <td>{{$post->title}}</td>
              <td>{{ str_limit( $post->content, 300, '...') }}</td>
              <td>{{$post->user->name}}</td>
              <td>
                <a href="{{route('post.show', ['post' => $post->id])}}" class="btn btn-info m-1">👁</a>
                <a href="{{route('post.edit', ['post' => $post->id])}}" class="btn btn-success m-1">✎</a>
                <a href="{{route('post.destroy', ['post' => $post->id])}}" class="btn btn-danger delete_post m-1">🗑</a>
              </td>
            </tr>
          @endforeach
      </tbody>
    </table>
    @else
    <div class="m-auto text-center">
      <a href="{{route('post.create')}}" class="btn btn-success ">Créer un article pour commencer</a>
    </div>
    @endif
  </div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">
    $(function(){
      $(".delete_post").click(function(e) {
        e.preventDefault();
        var href = $(this).attr('href');

       $.ajax({
             url: href,
             method: 'delete',
             headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
             success: function(){
                 alert('Article supprimé');
                 location.reload();
             }
         });
      });
    });
</script>
@endsection

resources/views/post/show.blade.php
@extends('layout.layout')
@section('title')
{{ $post->title }}
@endsection
@section('content')
<div class="container" style="min-height:570px;">
  <div class="post">
      <h1 class="pb-3">{{ $post->title }}
        @auth
          <a href="{{ route('post.edit', ['post' => $post->id]) }}" class="btn btn-warning">Éditer l'article</a>
        @endauth
      </h1>
      <div class="content" class="pb-3">
        <p>{{ $post->content }}</p>
      </div>
      <hr>
      <p class="text-right">- Par <em>{{ $post->user->name }}</em>, le {{ date('d/m/Y', strtotime($post->created_at)) }}</p>
  </div>
  @if(Session::has('message'))
    <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
  @endif
  <div class="comments">
    <h2>Vos réactions <small>({{ $post->comments->count() }} commentaires)</small></h2>
    @if($post->comments)

    @foreach($post->comments as $com)
      <span>De <em>{{ $com->user ? $com->user->name : 'Anonyme' }}</em>, le {{ date('d/m/Y à H:i:s', strtotime($com->created_at)) }}</span>
      @auth
        @if($user->id == $post->user_id)
          <a href="{{ route('comment.destroy', ['comment' => $com->id]) }}" class="delete_comment btn btn-danger btn-sm">Supprimer</a>
        @endif
      @endauth
      <p>{{ $com->content }}</p>
    @endforeach
    @endif
    <hr>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    {!! Form::open(['action' => ['CommentController@store']]) !!}
        <!-- {{ Form::token() }}
      possobilité de suppr par le posteur & dans le mail -->
           {!! Form::hidden('post_id', $post->id) !!}
          @auth
             {!! Form::hidden('user_id', $user->id) !!}
          @endauth
          <div class="form-group">
            {{ Form::label('content', 'Ajouter un commentaire : ') }}
            {{ Form::textarea('content', null, ['class' => 'form-control']) }}
            {{ Form::submit('Ajouter ce commentaire !', ['class' => 'btn btn-info mt-2 ']) }}
        </div>

    {{ Form::close() }}
  </div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">
    $(function(){
      $(".delete_comment").click(function(e) {
        e.preventDefault();
        var href = $(this).attr('href');

       $.ajax({
             url: href,
             method: 'delete',
             headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
             success: function(){
                 alert('Commentaire supprimé');
                 location.reload();
             }
         });
      });
    });
</script>
@endsection